### ISSUE TITLE
IAM requirements

### ISSUE THREAD

**Issue by soukicz** [scalefactory/s3audit#7]
There is mention in readme that we should use credentials from AWS Vault but there is no mention which permissions it actually requires - I would like to create IAM role with minimal permission scope.

**Comment by robbytaylor** [comment]
Hi @soukicz. Thanks for your interest in this project.

These actions should be sufficient:

```
s3:ListAllMyBuckets,
s3:GetBucketAcl,
s3:GetBucketLogging,
s3:GetBucketPolicy,
s3:GetBucketPublicAccessBlock,
s3:GetBucketVersioning,
s3:GetBucketWebsite,
s3:GetEncryptionConfiguration
```

Let me know how you get on with those.

**Comment by soukicz** [comment]
Thank you, it works!
